name: teste

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    

  deploy-dev:
    name: Deploy Desenvolvimento
    runs-on: windows-latest
    environment: desenv
    needs: [build]
    steps:
    
    - name: Teste
      run: echo 'Teste Deploy Desenv'
      
  deploy-hlmg:
    name: Deploy Homologacao
    runs-on: windows-latest
    environment: hmlg
    needs: [deploy-dev]
    steps:
    
    - name: Teste2
      run: echo 'Teste Deploy Homologacao'
      
  deploy-prod:
    name: Deploy Producao
    runs-on: windows-latest
    environment: prod
    needs: [deploy-hlmg]
    steps:
    
    - name: Teste3
      run: echo 'Teste Deploy Producao'
